"""
Import contacts from the Social Network Database.xlsx spreadsheet into the Network SQLite database.
Run this after the backend has been started at least once (to create tables).

Usage: python import_contacts.py
"""
import sqlite3
import os
from datetime import datetime

DB_PATH = os.path.join(os.path.dirname(__file__), "network.db")

CONTACTS = [
    {
        "name": "Jordan Hirsch",
        "phone": "214-497-0312",
        "email": "jhirsch@palantir.com",
        "how_we_met": "Palantir",
        "current_role": "Counselor, Palantir",
        "domain": "Industry/Policy",
        "tier": "Developing",
        "is_super_connector": False,
        "relationship_status": "In a relationship",
        "interests": None,
        "their_goals": None,
        "what_i_offer": "Crypto/regulatory insight; DC connections",
        "activity_prefs": None,
        "next_action": "Set up coffee or drinks",
        "notes": None,
        "linkedin_url": "https://www.linkedin.com/in/jordan-hirsch-85367a227/",
    },
    {
        "name": "Colleen Bloss",
        "phone": "469-955-3441",
        "email": None,
        "how_we_met": "Fmr. Grassley Crime Chief",
        "current_role": "AUSA",
        "domain": "Senate/Hill",
        "tier": "Developing",
        "is_super_connector": True,
        "relationship_status": None,
        "interests": None,
        "their_goals": None,
        "what_i_offer": None,
        "activity_prefs": "Dinner party",
        "next_action": "Ask her to set up drinks with a couple AUSAs",
        "notes": "Good connector to AUSAs",
        "linkedin_url": None,
    },
    {
        "name": "Austin Rogers",
        "phone": "850-819-8668",
        "email": None,
        "how_we_met": "Fmr. Grassley Civil Chief",
        "current_role": "GC for Rick Scott",
        "domain": "Senate/Hill",
        "tier": "Developing",
        "is_super_connector": False,
        "relationship_status": "In a relationship",
        "interests": None,
        "their_goals": None,
        "what_i_offer": None,
        "activity_prefs": "Drinks",
        "next_action": "Ask for drinks; be candid about wanting to meet people",
        "notes": "A little standoffish. Knows Will Simpson.",
        "linkedin_url": "https://www.linkedin.com/in/austin-rogers-b65729112/",
    },
    {
        "name": "Tom DeMatteo",
        "phone": None,
        "email": None,
        "how_we_met": "Chief Counsel for Lee",
        "current_role": "CC for Lee",
        "domain": "Senate/Hill",
        "tier": "Developing",
        "is_super_connector": True,
        "relationship_status": "Married",
        "interests": "Golf",
        "their_goals": None,
        "what_i_offer": "Events, social invites, cigars",
        "activity_prefs": "Golf, Dinner party (with wife), Poker/cigars, Happy hour, Coffees at work",
        "next_action": "Be persistent; dinner party with wife, golf, happy hour",
        "notes": "Busy with wife. Ask him to connect me with others.",
        "linkedin_url": None,
    },
    {
        "name": "DJ Sandavol",
        "phone": "404-775-9053",
        "email": None,
        "how_we_met": "Law school",
        "current_role": "CC for Kennedy",
        "domain": "Senate/Hill",
        "tier": "Developing",
        "is_super_connector": False,
        "relationship_status": "Married, recent baby",
        "interests": None,
        "their_goals": None,
        "what_i_offer": "Connect on Yale experience; shared background",
        "activity_prefs": "Double dinner with wife, Breakfast, Lunch",
        "next_action": "Lunch. Ask for connections. Connect on Yale.",
        "notes": "Quiet, but likely helpful if asked. Non-traditional background angle.",
        "linkedin_url": "https://www.linkedin.com/in/dj-sandoval-5b982a141/",
    },
    {
        "name": "Geoffrey Macleay",
        "phone": None,
        "email": None,
        "how_we_met": "Chief Counsel for Tillis",
        "current_role": "CC for Tillis",
        "domain": "Senate/Hill",
        "tier": "New",
        "is_super_connector": False,
        "relationship_status": "Unknown",
        "interests": None,
        "their_goals": None,
        "what_i_offer": None,
        "activity_prefs": "Coffee",
        "next_action": "Coffee",
        "notes": None,
        "linkedin_url": "https://www.linkedin.com/in/geoffrey-macleay-5a8a9913/",
    },
    {
        "name": "Ben Blackmon",
        "phone": None,
        "email": None,
        "how_we_met": "Chief for Blackburn",
        "current_role": "Chief for Blackburn",
        "domain": "Senate/Hill",
        "tier": "New",
        "is_super_connector": False,
        "relationship_status": "Unknown",
        "interests": None,
        "their_goals": None,
        "what_i_offer": None,
        "activity_prefs": "Coffee",
        "next_action": "Set up coffee",
        "notes": None,
        "linkedin_url": "https://www.linkedin.com/in/ben-blackmon/",
    },
    {
        "name": "Ethan Harper",
        "phone": "573-864-4195",
        "email": None,
        "how_we_met": "Friend / Chief of Schmidt",
        "current_role": "Chief of Schmidt",
        "domain": "Friend",
        "tier": "Cornerstone",
        "is_super_connector": True,
        "relationship_status": None,
        "interests": None,
        "their_goals": None,
        "what_i_offer": "Loyalty, events, genuine friendship",
        "activity_prefs": "Events co-organizer, Happy hours",
        "next_action": "1-on-1: ask straight up to help with events and intros",
        "notes": "CORNERSTONE ALLY & CONNECTOR. Great guy. Ask him to help get people to events.",
        "linkedin_url": "https://www.linkedin.com/in/ethan-harper/",
    },
    {
        "name": "Ben Daus",
        "phone": "339-223-3789",
        "email": None,
        "how_we_met": "Friend / Chief of Schmidt",
        "current_role": "Friend",
        "domain": "Friend",
        "tier": "Cornerstone",
        "is_super_connector": False,
        "relationship_status": None,
        "interests": None,
        "their_goals": None,
        "what_i_offer": "Loyalty; always build him up publicly",
        "activity_prefs": "Events, Parties",
        "next_action": "Plan events together. Ask for help. Give a gift.",
        "notes": "Cornerstone friend. Be grateful. Follow up.",
        "linkedin_url": "https://www.linkedin.com/in/ben-daus-6b145a18/",
    },
    {
        "name": "Joe Donato",
        "phone": "347-282-3548",
        "email": None,
        "how_we_met": "Friend",
        "current_role": "Military",
        "domain": "Military",
        "tier": "Cornerstone",
        "is_super_connector": False,
        "relationship_status": "Single",
        "interests": None,
        "their_goals": None,
        "what_i_offer": "Genuine friendship; vulnerability and honesty",
        "activity_prefs": "One-on-one hangout",
        "next_action": "1-on-1: open up about past, ask for help building network",
        "notes": "CORNERSTONE FRIEND. Will help.",
        "linkedin_url": "https://www.linkedin.com/in/jmd614/",
    },
    {
        "name": "Jack Kieffaber",
        "phone": "213-449-2866",
        "email": None,
        "how_we_met": "Friend",
        "current_role": "Policy (?)",
        "domain": "Friend",
        "tier": "Cornerstone",
        "is_super_connector": False,
        "relationship_status": "Single",
        "interests": "Dating",
        "their_goals": "Dating help",
        "what_i_offer": "Dating coaching/advice",
        "activity_prefs": "One-on-one, Cigars",
        "next_action": "1-on-1: offer dating advice, ask for networking help",
        "notes": "CORNERSTONE FRIEND. Ask every week for help.",
        "linkedin_url": "https://www.linkedin.com/in/jack-kieffaber-01aa041ab/",
    },
    {
        "name": "Kole Nichols",
        "phone": "701-361-1313",
        "email": None,
        "how_we_met": "Poker",
        "current_role": "Economics at White House",
        "domain": "Industry/Policy",
        "tier": "New",
        "is_super_connector": False,
        "relationship_status": None,
        "interests": "Poker",
        "their_goals": None,
        "what_i_offer": None,
        "activity_prefs": "Poker",
        "next_action": "Invite to poker night or happy hour",
        "notes": None,
        "linkedin_url": "https://www.linkedin.com/in/kole-nichols-34013b162/",
    },
    {
        "name": "Will Simpson",
        "phone": "870-615-4080",
        "email": None,
        "how_we_met": "Work",
        "current_role": "Hawley staff",
        "domain": "Senate/Hill",
        "tier": "Developing",
        "is_super_connector": False,
        "relationship_status": None,
        "interests": "Golf",
        "their_goals": None,
        "what_i_offer": "Loyalty; wing man ethos",
        "activity_prefs": "Golf",
        "next_action": "Golf + candid talk about networking",
        "notes": "Could be a good friend. Candid conversation about moving to DC.",
        "linkedin_url": "https://www.linkedin.com/in/simpsonwill/",
    },
    {
        "name": "Andrew Sayer",
        "phone": "858-414-8454",
        "email": None,
        "how_we_met": "Cigar night with Jack",
        "current_role": "Unknown",
        "domain": "Social",
        "tier": "New",
        "is_super_connector": False,
        "relationship_status": "In a relationship (out of town)",
        "interests": None,
        "their_goals": None,
        "what_i_offer": "Build him up socially; be a good connector for him",
        "activity_prefs": "Cigars, Events",
        "next_action": "Text soon. Set up 1-on-1. Explore interests.",
        "notes": "Seems like a good guy. Low-key.",
        "linkedin_url": "https://www.linkedin.com/in/andrew-sayer-4796a184/",
    },
    {
        "name": "Chris McGuire",
        "phone": "646-369-7948",
        "email": None,
        "how_we_met": "AI Hearing",
        "current_role": "CFR",
        "domain": "Industry/Policy",
        "tier": "Developing",
        "is_super_connector": False,
        "relationship_status": "Married with kids",
        "interests": "AI policy",
        "their_goals": None,
        "what_i_offer": "CFTC/regulatory perspective on AI",
        "activity_prefs": "Lunch",
        "next_action": "Set up lunch (has been unresponsive - try again)",
        "notes": "Good guy. Liberal. Has been unresponsive.",
        "linkedin_url": "https://www.linkedin.com/in/cmcguire89/",
    },
    {
        "name": "Tucker Akin",
        "phone": "901-456-6901",
        "email": None,
        "how_we_met": "Grassley Investigative Counsel",
        "current_role": "Grassley staff",
        "domain": "Senate/Hill",
        "tier": "New",
        "is_super_connector": False,
        "relationship_status": "Single",
        "interests": None,
        "their_goals": None,
        "what_i_offer": "Social invites; make him feel included",
        "activity_prefs": "Cigars/whiskey",
        "next_action": "Invite to cigar/whiskey night",
        "notes": "Young. Would appreciate being invited. May know others.",
        "linkedin_url": "https://www.linkedin.com/in/tucker-akin-3786b1177/",
    },
    {
        "name": "Ian Swenson",
        "phone": "512-310-1519",
        "email": None,
        "how_we_met": "Through Lorraine etc.",
        "current_role": "Law firm",
        "domain": "Social",
        "tier": "Developing",
        "is_super_connector": False,
        "relationship_status": "Married",
        "interests": "Whiskey, sports",
        "their_goals": None,
        "what_i_offer": "Friendship; double dates",
        "activity_prefs": "Whiskey, Sports at home, Double dates",
        "next_action": "Invite for 1-on-1: whiskey and game at my place",
        "notes": "Perfect for building friendship. Double dates would be great.",
        "linkedin_url": None,
    },
    {
        "name": "Brian McGrail",
        "phone": None,
        "email": None,
        "how_we_met": "Law school, lobbyist",
        "current_role": "AI lobbying",
        "domain": "Industry/Policy",
        "tier": "New",
        "is_super_connector": True,
        "relationship_status": None,
        "interests": "AI policy, networking events",
        "their_goals": None,
        "what_i_offer": "CFTC perspective on AI regulation",
        "activity_prefs": "Coffee, Cigars/whiskey, Networking events",
        "next_action": "Coffee outside, then game or cigar/whiskey night",
        "notes": "Nerdy but worth inviting. Probably knows networking events.",
        "linkedin_url": None,
    },
    {
        "name": "Grace",
        "phone": None,
        "email": None,
        "how_we_met": "Through Catherine",
        "current_role": "Unknown",
        "domain": "Social",
        "tier": "Developing",
        "is_super_connector": True,
        "relationship_status": "In a relationship",
        "interests": None,
        "their_goals": None,
        "what_i_offer": None,
        "activity_prefs": None,
        "next_action": "Ask her to connect me with her boyfriend for lunch",
        "notes": "Good for networking. Always include Catherine when meeting.",
        "linkedin_url": None,
    },
    {
        "name": "Grace's Boyfriend",
        "phone": None,
        "email": None,
        "how_we_met": "Through Grace/Catherine",
        "current_role": "Unknown (high status)",
        "domain": "Social",
        "tier": "New",
        "is_super_connector": False,
        "relationship_status": "Dating Grace",
        "interests": "DC social scene",
        "their_goals": None,
        "what_i_offer": "Loyalty; team mentality",
        "activity_prefs": "Lunch, Double dates",
        "next_action": "Ask Grace to set up lunch",
        "notes": "High status. Test carefully in group settings first.",
        "linkedin_url": None,
    },
    {
        "name": "CB",
        "phone": None,
        "email": None,
        "how_we_met": "Fmr. Moody Chief",
        "current_role": "Unknown current",
        "domain": "Senate/Hill",
        "tier": "New",
        "is_super_connector": False,
        "relationship_status": "Unknown",
        "interests": None,
        "their_goals": None,
        "what_i_offer": None,
        "activity_prefs": "Coffee, Lunch",
        "next_action": "Set up coffee/lunch",
        "notes": "Cool, never hung out. Seems chill.",
        "linkedin_url": None,
    },
    {
        "name": "Helen Boon",
        "phone": None,
        "email": None,
        "how_we_met": None,
        "current_role": "Unknown",
        "domain": "Social",
        "tier": "Dormant",
        "is_super_connector": False,
        "relationship_status": None,
        "interests": None,
        "their_goals": None,
        "what_i_offer": "Good for introducing to Jack",
        "activity_prefs": None,
        "next_action": "Reframe relationship carefully",
        "notes": "Good person. Could be good for people like Jack.",
        "linkedin_url": None,
    },
    {
        "name": "Tyler Dobbs",
        "phone": "316-641-0938",
        "email": None,
        "how_we_met": "Through Catherine",
        "current_role": "Unknown",
        "domain": "Social",
        "tier": "New",
        "is_super_connector": True,
        "relationship_status": "Married with kids",
        "interests": "Natural law, family, conservative values, socializing kids",
        "their_goals": "Connector role",
        "what_i_offer": "Genuine conservative values; admiration for his family",
        "activity_prefs": "Lunch, Conservative events",
        "next_action": "Get Catherine to connect; lunch. Ask about conservative events.",
        "notes": "Very conservative. Thinks of himself as a connector. GREAT conservative networking hub -- ask to keep in loop with events.",
        "linkedin_url": "https://www.linkedin.com/in/tyler-dobbs-3bb0752ba/",
    },
    {
        "name": "Charlie Albus",
        "phone": "314-591-4953",
        "email": "albuscharles34@gmail.com",
        "how_we_met": "Through John",
        "current_role": "Wash U student / Son of US Attorney W.D. MO",
        "domain": "Social",
        "tier": "New",
        "is_super_connector": False,
        "relationship_status": "Single",
        "interests": None,
        "their_goals": None,
        "what_i_offer": None,
        "activity_prefs": None,
        "next_action": None,
        "notes": "Great guy. Lives in MO.",
        "linkedin_url": None,
    },
    {
        "name": "Noah Hall",
        "phone": "561-347-3623",
        "email": None,
        "how_we_met": "Bible study",
        "current_role": "Marines (?)",
        "domain": "Military",
        "tier": "New",
        "is_super_connector": False,
        "relationship_status": "Unknown",
        "interests": "Faith",
        "their_goals": None,
        "what_i_offer": None,
        "activity_prefs": None,
        "next_action": None,
        "notes": None,
        "linkedin_url": None,
    },
    {
        "name": "Bobby Crossin",
        "phone": "317-341-1251",
        "email": None,
        "how_we_met": "Through Jack K",
        "current_role": "AFL Legal",
        "domain": "Industry/Policy",
        "tier": "New",
        "is_super_connector": False,
        "relationship_status": None,
        "interests": None,
        "their_goals": None,
        "what_i_offer": None,
        "activity_prefs": None,
        "next_action": None,
        "notes": None,
        "linkedin_url": "https://www.linkedin.com/in/bobby-cornett-47010126/",
    },
]


def import_contacts():
    if not os.path.exists(DB_PATH):
        print(f"Database not found at {DB_PATH}")
        print("Start the backend first to create the database, then run this script.")
        return

    conn = sqlite3.connect(DB_PATH)
    conn.row_factory = sqlite3.Row
    cursor = conn.cursor()

    # Check if contacts already exist
    cursor.execute("SELECT COUNT(*) as cnt FROM contacts")
    count = cursor.fetchone()["cnt"]
    if count > 0:
        print(f"Database already has {count} contacts. Skipping import.")
        print("To re-import, delete network.db and restart the backend first.")
        conn.close()
        return

    now = datetime.utcnow().isoformat()

    for c in CONTACTS:
        cursor.execute(
            """
            INSERT INTO contacts (
                name, phone, email, how_we_met, current_role, domain, tier,
                is_super_connector, relationship_status, interests, their_goals,
                what_i_offer, activity_prefs, next_action, notes, linkedin_url,
                created_at, updated_at
            ) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
            """,
            (
                c["name"],
                c["phone"],
                c["email"],
                c["how_we_met"],
                c["current_role"],
                c["domain"],
                c["tier"],
                c["is_super_connector"],
                c["relationship_status"],
                c["interests"],
                c["their_goals"],
                c["what_i_offer"],
                c["activity_prefs"],
                c["next_action"],
                c["notes"],
                c["linkedin_url"],
                now,
                now,
            ),
        )

    conn.commit()
    print(f"Successfully imported {len(CONTACTS)} contacts.")

    # Print summary
    cursor.execute(
        "SELECT tier, COUNT(*) as cnt FROM contacts GROUP BY tier ORDER BY cnt DESC"
    )
    print("\nBy tier:")
    for row in cursor.fetchall():
        print(f"  {row['tier']}: {row['cnt']}")

    cursor.execute(
        "SELECT domain, COUNT(*) as cnt FROM contacts GROUP BY domain ORDER BY cnt DESC"
    )
    print("\nBy domain:")
    for row in cursor.fetchall():
        print(f"  {row['domain']}: {row['cnt']}")

    cursor.execute(
        "SELECT COUNT(*) as cnt FROM contacts WHERE is_super_connector = 1"
    )
    print(f"\nSuper-connectors: {cursor.fetchone()['cnt']}")

    conn.close()


if __name__ == "__main__":
    import_contacts()
